name: phone_sign_in
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.7.1
  firebase_auth: 4.2.10
  font_awesome_flutter: 10.4.0
  google_fonts: 4.0.3
  shimmer: 2.0.0
  intl: 0.17.0
  flutter_easyloading: 3.0.5
  intl_phone_number_input: 0.7.2
  modal_bottom_sheet: 3.0.0-pre
  uuid: 3.0.7
  flutter_otp_text_field: 1.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

